加入爬取摩点 star，notion 自动化的代码
Hikaru518/mad-roots pull request #20
Opened 2023-09-03 14:11 UTC by Hikaru518

2023-09-03 14:17 UTC, sichaozhang1112 requested changes
good work.

2023-09-03 14:17 UTC, sichaozhang1112 commented on notion_integration/modian_interface.py
> +    print("1111")
no need for this debug info

2023-09-03 15:22 UTC, Hikaru518 commented on notion_integration/modian_interface.py
> +    print("1111")
改了

2023-09-04 15:30 UTC, sichaozhang1112 approved these changes

2023-09-04 15:32 UTC, merged